"""
Bitrix24 API client with token management and URL-based authentication
"""

import json
import requests
from typing import Dict, List, Optional
from datetime import datetime


class BitrixAPI:
    """
    Bitrix24 API client using token-based REST authentication
    
    IMPORTANT: How to get token and user_id for REST API access
    ────────────────────────────────────────────────────────────
    
    1. Token Acquisition:
       • Run: python3 main.py
       • Opens Chromium browser
       • Auto-logs in with saved cookies
       • Fetches token via /me: endpoint in browser
       • Saves to .env as API_TOKEN
    
    2. User ID:
       • Extracted from token response (USER_ID field)
       • Saved to .env as API_USER_ID
       • Alternative: From cookies (UAD_AVATAR)
    
    3. REST API Access:
       • URL format: /rest/{user_id}/{token}/{method}
       • Example: /rest/2611/pkc4eycs2shrl0ko/user.current
       • Token serves as authentication (no separate Bearer header needed)
    
    API URL Construction:
    ─────────────────────
    https://ugautodetal.ru/rest/{user_id}/{token}/{method}
    
    Request:
        POST https://ugautodetal.ru/rest/2611/pkc4eycs2shrl0ko/im.dialog.list
        Content-Type: application/json
        
        {"LIMIT": 10}
    
    Response:
        {
          "result": [
            {"ID": "40", "TITLE": "Main Chat"},
            {"ID": "41", "TITLE": "Support"}
          ]
        }
    """
    
    def __init__(self, user_id: int, token: str, base_domain: str = "https://ugautodetal.ru"):
        """
        Initialize Bitrix API client with user_id and token
        
        REQUIREMENTS:
        ─────────────
        To use this API, you MUST have:
        1. API_TOKEN: Obtained from browser via main.py
        2. API_USER_ID: User ID associated with the token
        
        Both are saved to .env after running: python3 main.py
        
        Args:
            user_id: User ID for API authentication (int or convertible to int)
                     • Must match the user who generated the token
                     • Found in: .env as API_USER_ID
                     • Example: 2611
            
            token: API token obtained via browser authentication
                   • Generated by: python3 main.py
                   • Saved to: .env as API_TOKEN
                   • Format: alphanumeric string (e.g., pkc4eycs2shrl0ko)
                   • Used in URL: /rest/{user_id}/{token}/{method}
            
            base_domain: Base domain for Bitrix instance (default: https://ugautodetal.ru)
                        • Set to your Bitrix24 instance URL
                        • Example: https://company.bitrix24.com
        
        Raises:
            TypeError: If user_id cannot be converted to int
            ValueError: If token is empty
        
        Example:
            from api.bitrix_api import BitrixAPI
            import os
            from dotenv import load_dotenv
            
            load_dotenv()
            api = BitrixAPI(
                user_id=int(os.getenv('API_USER_ID')),
                token=os.getenv('API_TOKEN')
            )
        """
        self.user_id = user_id
        self.token = token
        self.base_domain = base_domain.rstrip('/')
        self.base_url = f"{self.base_domain}/rest"
        
        # Validate credentials
        if not self.token:
            raise ValueError("API token cannot be empty. Run 'python3 main.py' to get token.")
        
        if not self.user_id:
            raise ValueError("user_id cannot be empty. Run 'python3 main.py' to get user_id.")
        
        self.session = requests.Session()
        self.session.headers.update({
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'User-Agent': 'Python-Bitrix-Chat-Client/1.0'
        })
        
        # Set longer timeout for debugging
        self.session.timeout = 60
        
        print(f"Initialized API with user_id: {self.user_id}")
        print(f"API base URL: {self.base_url}/{self.user_id}/{self.token[:20]}...user.current")
    
    def _get_api_url(self, method: str) -> str:
        """
        Get full API URL for a method
        
        Args:
            method: API method name
            
        Returns:
            Full URL with user_id and token
        """
        return f"{self.base_url}/{self.user_id}/{self.token}/{method}"
    
    def call_method(self, method: str, params: Dict = None) -> Dict:
        """
        Call Bitrix API method with user_id and token in URL
        
        Args:
            method: API method name
            params: Request parameters
            
        Returns:
            API response as dictionary
        """
        url = self._get_api_url(method)
        
        try:
            start_time = datetime.now()
            response = self.session.post(url, json=params or {}, timeout=60)
            elapsed = (datetime.now() - start_time).total_seconds()
            
            try:
                result = response.json()
                return result
            except json.JSONDecodeError as e:
                text = response.text[:1000]
                return {"error": f"JSON decode error: {e}", "text": text}
                
        except requests.Timeout:
            return {"error": "Request timeout", "result": None}
        except requests.RequestException as e:
            return {"error": str(e), "result": None}
        except Exception as e:
            return {"error": str(e), "result": None}
    
    # User profile methods
    def get_current_profile(self) -> Dict:
        return self.call_method("profile")
    
    def list_managers(self) -> Dict:
        return self.call_method("uad.shop.api.profile.listManagers")
    
    # Chat methods
    def get_groups(self) -> Dict:
        return self.call_method("uad.shop.api.chat.getGroups")
    
    def get_messages(self, group_id: int) -> Dict:
        return self.call_method("uad.shop.api.chat.getMessages", {"group": group_id})
    
    def get_user_news_content(self) -> Dict:
        return self.call_method("uad.shop.api.chat.getUserNewsContent")
    
    def clear_notifications(self, group_id: int) -> Dict:
        return self.call_method("uad.shop.api.chat.clearNotifications", {"group": group_id})
    
    def get_notifications(self) -> Dict:
        return self.call_method("uad.shop.api.chat.getNotifications")
    
    def create_group(self, title: str, message: str, user_ids: List[int], 
                    document_id: str = "") -> Dict:
        params = {
            "title": title,
            "message": message,
            "userIds": user_ids
        }
        
        if document_id:
            params["documentId"] = document_id
            
        return self.call_method("uad.shop.api.chat.createGroup", params)
    
    def add_message(self, group, message: str) -> Dict:
        group_data = {
            "id": group.id,
            "title": group.title or "",
            "participants": group.participants,
            "participant_names": group.participant_names,
            "unread_count": group.unread_count,
            "type": group.type,
            "site": group.site,
            "author": group.author or 0,
            "date": group.date or "",
            "pinned": group.pinned
        }
        
        group_json = json.dumps(group_data, ensure_ascii=False)
        
        return self.call_method("uad.shop.api.chat.addMessage", {
            "group": group_json,
            "message": message
        })
    
    def get_attachment(self, msg_id: int, att_id: int) -> Dict:
        return self.call_method("uad.shop.api.chat.getAttachment", {
            "msgId": msg_id,
            "attId": att_id
        })
    
    def add_group_participants(self, chat_id: int, user_ids: List[int]) -> Dict:
        return self.call_method("uad.shop.api.chat.addGroupParticipants", {
            "chatId": chat_id,
            "userIds": user_ids
        })
    
    def remove_group_participants(self, chat_id: int, user_ids: List[int]) -> Dict:
        return self.call_method("uad.shop.api.chat.removeGroupParticipants", {
            "chatId": chat_id,
            "userIds": user_ids
        })
    
    def activate_subscriptions(self) -> Dict:
        """Activate WebSocket subscriptions"""
        try:
            # First try the chat-specific method
            result = self.call_method("uad.shop.api.chat.activateSubscriptions")
            
            if result and not result.get("error"):
                return result
            
            # Fallback to generic pull method
            result = self.call_method("pull.config.get")
            
            if result and not result.get("error"):
                return result
            
            # If both fail, return empty result
            return {"result": {}}
                
        except Exception as e:
            return {"error": str(e)}
    
    # Customer methods
    def get_customers(self) -> Dict:
        """Get all customers/contacts - using proper chat API"""
        # Try different API endpoints
        endpoints = [
            "uad.shop.api.customer.getAll"
        ]
        
        for endpoint in endpoints:
            data = self.call_method(endpoint)
            
            if data and not data.get("error"):
                return data
        
        # If all fail, return empty result
        return {"result": []}
    
    def search_customer(self, query: str) -> Dict:
        """Search customers/contractors"""
        return self.call_method("crm.contact.list", {
            "filter": {"%NAME": query, "%LAST_NAME": query},
            "select": ["ID", "NAME", "LAST_NAME", "EMAIL", "PHONE"],
            "start": 0,
            "limit": 50
        })
    
    # Document methods
    def get_documents(self, doc_type: str, contractor_id: str = "", document_id: str = "") -> Dict:
        """Get documents - simplified version"""
        return self.call_method("uad.shop.api.docview.getDocuments", {
            "page": 0,
            "filter": {"type": doc_type}
        })
    
    # API Token Management Methods
    def get_token_api(self) -> Dict:
        """Get existing API token"""
        return self.call_method("base.api.user.getTokenApi")
    
    def create_token_api(self, name: str = "Python Chat Client", 
                        expires_in_days: int = 365) -> Dict:
        """
        Create new API token
        
        Args:
            name: Token name for identification
            expires_in_days: Token expiration in days (default: 365)
        """
        params = {
            "name": name,
            "expires_in_days": expires_in_days
        }
        return self.call_method("base.api.user.createTokenApi", params)
    
    def revoke_token_api(self, token_id: str) -> Dict:
        """Revoke/delete API token"""
        return self.call_method("base.api.user.revokeTokenApi", {"token_id": token_id})
    
    def list_tokens_api(self) -> Dict:
        """List all API tokens"""
        return self.call_method("base.api.user.listTokensApi")
    
    def get_current_token_info(self) -> Dict:
        """Get information about current API token"""
        return self.call_method("base.api.user.getCurrentTokenInfo")